### ISSUE TITLE
Add a way to test in localhost

### ISSUE THREAD

**Issue by a1phyr** [jplatte/caniuse.rs#12]
Currently `x.py` only allow to build the website or to deploy it with SSH on the `caniuse.rs` server.

it would be great to be able to server it locally, eg `x.py run 8000` to serve it on http://localhost:8000.

**Comment by jplatte** [comment]
Sounds good! What I've done to test so far is run `python -m http.server` in `public`. Shouldn't be too hard to integrate this into `x.py`. I would prefer `serve` over run, and the port should probably be optional (8000 seems like a reasonable default, and is also what `http.server` defaults to).

One additional thing that could be done if this is integrated in `x.py` is serving `index.html` when no matching file is found in `public` (such that reloading the page when inside a sub-route doesn't get you a 404), but that doesn't initially have to be part of this feature.

Are you familiar with Python / do you want to work on this?
