### ISSUE TITLE
Rust 1.49 and "types with a custom Drop implementation in unions"

### ISSUE THREAD

**Issue by tarcieri** [jplatte/caniuse.rs#15]
Regarding this: https://caniuse.rs/features/drop_types_in_union

Perhaps I'm misunderstanding, but this is possible as of Rust 1.49 by declaring the members of a union as `ManuallyDrop`.

**Comment by tarcieri** [comment]
Sure, that works

**Comment by jplatte** [comment]
Fixed in f33e1920ed83921c70ea875cb96819f7178ca07d. Thanks for the report 🙂
