### ISSUE TITLE
Recently stabilised is in increasing order of rust versions

### ISSUE THREAD

**Issue by CGMossa** [jplatte/caniuse.rs#23]
The Recently Stabilised pane is sorted the other way that I would expect.

Here's the image:

![image](https://user-images.githubusercontent.com/1063624/136978695-0373ff68-f4c7-4b53-bacd-1041c3628faf.png)

Is this intentional?

**Comment by jplatte** [comment]
Alright, thanks for the report anyways. If other people feel that the order should be reversed here, I'd definitely be open to change it but for now I'll leave it as-is.
