### ISSUE TITLE
Consider using .toml files instead of .md files

### ISSUE THREAD

**Issue by not-my-profile** [jplatte/caniuse.rs#30]
a407f821da484bdef0d361770b0c66590935a61a split `features.toml` into many small files ... which of course makes sense maintenance-wise. The data is now however stored in `.md` files with a TOML frontmatter like

```
+++
title = "`debug_assert_ne!`"
rfc_id = 1653
impl_pr_id = 35074
tracking_issue_id = 35073
+++
```

this makes the data harder to work with. If you want to use the data for any other purpose you need to write your own parser for this non-standardized format. It also makes contributing a bit harder ... because it's not immediately clear what format these files have. `.toml` files are well understood by Rust programmers so I think they really are the natural choice.

**Comment by jplatte** [comment]
Having frontmatter in markdown files is a common thing and there's really not that much parsing to it. The idea with this was that some features could include an extended description after this frontmatter.

However, I haven't actually gotten around to implementing this and I don't see myself doing it in the near future. I guess it would only apply to *some* features anyways, so if you want to send a PR switching it back to TOML (if there's ever an extended description, it could also be a multiline string in TOML), I'm okay with merging that.
