### ISSUE TITLE
Missing feature about inline assembly

### ISSUE THREAD

**Issue by slanterns** [jplatte/caniuse.rs#51]
As inline assembly (asm!, global_asm!) is [stabilized](https://github.com/rust-lang/rust/pull/91728/) in 1.59.0, could you please consider adding it to the feature list? Thanks!

**Comment by jplatte** [comment]
Done: 7d9e00deb9279ba8cb53d134bf28d624d18b4232

You can also submit PRs for additional data, it's as easy as creating the `.toml` file :)
