### ISSUE TITLE
Could not find "abi_thiscall" nightly feature

### ISSUE THREAD

**Issue by pravic** [jplatte/caniuse.rs#6]
PR: https://github.com/rust-lang/rust/pull/42058
Tracking issue: https://github.com/rust-lang/rust/issues/42202

**Comment by jplatte** [comment]
In general, I don't have many unstable and long-stabilized features listed on caniuse.rs yet. I can easily add this one though :)

**Comment by jplatte** [comment]
Done in f9ece58.

**Comment by pravic** [comment]
> I don't have many unstable

Sigh. It would be really great to have a single informational source of those features.

Thanks for the adding!

**Comment by jplatte** [comment]
A thirdparty site is inevitably not going to be up-to-date all the time. But if you want to improve the unstable feature coverage of caniuse.rs, I'd be happy about PRs that add the data for them.
