### ISSUE TITLE
Scoped threads are stable

### ISSUE THREAD

**Issue by DoubleHyphen** [jplatte/caniuse.rs#63]
Per https://doc.rust-lang.org/stable/std/thread/fn.scope.html , it would appear that scoped threads have been stable since the previous version already. However, `caniuse.rs` lists them as unstable. Is there a specific reason for this?

**Comment by jplatte** [comment]
Haha no, no specific reason. It's just that the data is maintained by hand and I haven't been updating it in a little while. I also need to mark the latest stable as stable. There's also the fact that doing this for library features is annoying redundant work, I've been wanting to automate it more for a long time but it's not a project I'm excited about so it's been on the back-burner and likely going to stay that while for very long unless somebody else takes it up.

**Comment by jplatte** [comment]
Updated.
