### ISSUE TITLE
Duplicate "nul terminated `Vec<u8>` to `CString` conversions" entry

### ISSUE THREAD

**Issue by DropDemBits** [jplatte/caniuse.rs#74]
There's a redundant entry (under "nul terminated `Vec<u8>` to `CString` conversions") for the `cstring_from_vec_with_nul` that's still marked as unstable, even though there are entries for both stabilized methods.

**Comment by jplatte** [comment]
Fixed in 2d374e677f45553667b0d15c317cf710a0d27899, thanks for the report!
